//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Howell {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Howell.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {0} contains currently 1 element. 的本地化字符串。
        /// </summary>
        internal static string CollectionContainsCurrently1Element {
            get {
                return ResourceManager.GetString("CollectionContainsCurrently1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} contains currently {1} elements. 的本地化字符串。
        /// </summary>
        internal static string CollectionContainsCurrentlyXElements {
            get {
                return ResourceManager.GetString("CollectionContainsCurrentlyXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is currently a null reference. 的本地化字符串。
        /// </summary>
        internal static string CollectionIsCurrentlyANullReference {
            get {
                return ResourceManager.GetString("CollectionIsCurrentlyANullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be empty 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldBeEmpty {
            get {
                return ResourceManager.GetString("CollectionShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain 1 element 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContain1Element {
            get {
                return ResourceManager.GetString("CollectionShouldContain1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain all of {1} 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainAllOfX {
            get {
                return ResourceManager.GetString("CollectionShouldContainAllOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain at least one of {1} 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainAtLeastOneOfX {
            get {
                return ResourceManager.GetString("CollectionShouldContainAtLeastOneOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain less than 1 element 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainLessThan1Element {
            get {
                return ResourceManager.GetString("CollectionShouldContainLessThan1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain less than {1} elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainLessThanXElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainLessThanXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain more than 1 element 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainMoreThan1Element {
            get {
                return ResourceManager.GetString("CollectionShouldContainMoreThan1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain more than {1} elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainMoreThanXElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainMoreThanXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain {1} 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainX {
            get {
                return ResourceManager.GetString("CollectionShouldContainX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain {1} elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainXElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain {1} or less elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainXOrLessElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainXOrLessElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain {1} or more elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldContainXOrMoreElements {
            get {
                return ResourceManager.GetString("CollectionShouldContainXOrMoreElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be empty 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("CollectionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain 1 element 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContain1Element {
            get {
                return ResourceManager.GetString("CollectionShouldNotContain1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain all of {1} 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainAllOfX {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainAllOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain any of {1} 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainAnyOfX {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainAnyOfX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain more than 1 element 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainLessThan1Element {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainLessThan1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain less than {1} elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainLessThanXElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainLessThanXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain more than 1 element 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainMoreThan1Element {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainMoreThan1Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain more than {1} elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainMoreThanXElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainMoreThanXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain {1} 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainX {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain {1} elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainXElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainXElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain {1} or less elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainXOrLessElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainXOrLessElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain {1} or more elements 的本地化字符串。
        /// </summary>
        internal static string CollectionShouldNotContainXOrMoreElements {
            get {
                return ResourceManager.GetString("CollectionShouldNotContainXOrMoreElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified type {0} is not supported. The type must be concrete and have a public constructor with a single string argument. 的本地化字符串。
        /// </summary>
        internal static string ExceptionTypeIsInvalid {
            get {
                return ResourceManager.GetString("ExceptionTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{1}&apos; should hold for {0} 的本地化字符串。
        /// </summary>
        internal static string LambdaXShouldHoldForValue {
            get {
                return ResourceManager.GetString("LambdaXShouldHoldForValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Postcondition failed. 的本地化字符串。
        /// </summary>
        internal static string PostconditionFailed {
            get {
                return ResourceManager.GetString("PostconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Postcondition &apos;{0}&apos; failed. 的本地化字符串。
        /// </summary>
        internal static string PostconditionXFailed {
            get {
                return ResourceManager.GetString("PostconditionXFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be 1 character long 的本地化字符串。
        /// </summary>
        internal static string StringShouldBe1CharacterLong {
            get {
                return ResourceManager.GetString("StringShouldBe1CharacterLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be an empty string 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeEmpty {
            get {
                return ResourceManager.GetString("StringShouldBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be longer or equal to 1 character 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeLongerOrEqualTo1Character {
            get {
                return ResourceManager.GetString("StringShouldBeLongerOrEqualTo1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be longer or equal to {1} characters 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeLongerOrEqualToXCharacters {
            get {
                return ResourceManager.GetString("StringShouldBeLongerOrEqualToXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be longer than 1 character 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeLongerThan1Character {
            get {
                return ResourceManager.GetString("StringShouldBeLongerThan1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be longer than {1} characters 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeLongerThanXCharacters {
            get {
                return ResourceManager.GetString("StringShouldBeLongerThanXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be null or an empty string 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringShouldBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be null, empty or consists only of white-space characters. 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringShouldBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be shorter or equal to 1 character 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeShorterOrEqualTo1Character {
            get {
                return ResourceManager.GetString("StringShouldBeShorterOrEqualTo1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be shorter or equal to {1} characters 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeShorterOrEqualToXCharacters {
            get {
                return ResourceManager.GetString("StringShouldBeShorterOrEqualToXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be shorter than 1 character 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeShorterThan1Character {
            get {
                return ResourceManager.GetString("StringShouldBeShorterThan1Character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be shorter than {1} characters 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeShorterThanXCharacters {
            get {
                return ResourceManager.GetString("StringShouldBeShorterThanXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be {1} characters long 的本地化字符串。
        /// </summary>
        internal static string StringShouldBeXCharactersLong {
            get {
                return ResourceManager.GetString("StringShouldBeXCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should contain {1} 的本地化字符串。
        /// </summary>
        internal static string StringShouldContainX {
            get {
                return ResourceManager.GetString("StringShouldContainX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should end with {1} 的本地化字符串。
        /// </summary>
        internal static string StringShouldEndWithX {
            get {
                return ResourceManager.GetString("StringShouldEndWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should match pattern {1} 的本地化字符串。
        /// </summary>
        internal static string StringShouldMatchPatternX {
            get {
                return ResourceManager.GetString("StringShouldMatchPatternX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be 1 character long 的本地化字符串。
        /// </summary>
        internal static string StringShouldNotBe1CharacterLong {
            get {
                return ResourceManager.GetString("StringShouldNotBe1CharacterLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be an empty string 的本地化字符串。
        /// </summary>
        internal static string StringShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("StringShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be null or an empty string 的本地化字符串。
        /// </summary>
        internal static string StringShouldNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("StringShouldNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be null, and empty string or consists only of white-space characters. 的本地化字符串。
        /// </summary>
        internal static string StringShouldNotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("StringShouldNotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be {1} characters long 的本地化字符串。
        /// </summary>
        internal static string StringShouldNotBeXCharactersLong {
            get {
                return ResourceManager.GetString("StringShouldNotBeXCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not contain {1} 的本地化字符串。
        /// </summary>
        internal static string StringShouldNotContainX {
            get {
                return ResourceManager.GetString("StringShouldNotContainX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not end with {1} 的本地化字符串。
        /// </summary>
        internal static string StringShouldNotEndWithX {
            get {
                return ResourceManager.GetString("StringShouldNotEndWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not start with {1} 的本地化字符串。
        /// </summary>
        internal static string StringShouldNotStartWithX {
            get {
                return ResourceManager.GetString("StringShouldNotStartWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should start with {1} 的本地化字符串。
        /// </summary>
        internal static string StringShouldStartWithX {
            get {
                return ResourceManager.GetString("StringShouldStartWithX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The actual value is 1 character long. 的本地化字符串。
        /// </summary>
        internal static string TheActualValueIs1CharacterLong {
            get {
                return ResourceManager.GetString("TheActualValueIs1CharacterLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The actual value is {1}. 的本地化字符串。
        /// </summary>
        internal static string TheActualValueIsX {
            get {
                return ResourceManager.GetString("TheActualValueIsX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The actual value is {1} characters long. 的本地化字符串。
        /// </summary>
        internal static string TheActualValueIsXCharactersLong {
            get {
                return ResourceManager.GetString("TheActualValueIsXCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be a number 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeANumber {
            get {
                return ResourceManager.GetString("ValueShouldBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be between {1} and {2} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeBetweenXAndY {
            get {
                return ResourceManager.GetString("ValueShouldBeBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be equal to {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldBeEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be false 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeFalse {
            get {
                return ResourceManager.GetString("ValueShouldBeFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be greater than or equal to {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeGreaterThanOrEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldBeGreaterThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be greater than {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeGreaterThanX {
            get {
                return ResourceManager.GetString("ValueShouldBeGreaterThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be infinity 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeInfinity {
            get {
                return ResourceManager.GetString("ValueShouldBeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be negative infinity 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeNegativeInfinity {
            get {
                return ResourceManager.GetString("ValueShouldBeNegativeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be null 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeNull {
            get {
                return ResourceManager.GetString("ValueShouldBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be of type {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeOfTypeX {
            get {
                return ResourceManager.GetString("ValueShouldBeOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be positive infinity 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBePositiveInfinity {
            get {
                return ResourceManager.GetString("ValueShouldBePositiveInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be smaller than or equal to {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeSmallerThanOrEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldBeSmallerThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be smaller than {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeSmallerThanX {
            get {
                return ResourceManager.GetString("ValueShouldBeSmallerThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be true 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeTrue {
            get {
                return ResourceManager.GetString("ValueShouldBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be unequal to {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeUnequalToX {
            get {
                return ResourceManager.GetString("ValueShouldBeUnequalToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should be valid 的本地化字符串。
        /// </summary>
        internal static string ValueShouldBeValid {
            get {
                return ResourceManager.GetString("ValueShouldBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be a number 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeANumber {
            get {
                return ResourceManager.GetString("ValueShouldNotBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be between {1} and {2} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeBetweenXAndY {
            get {
                return ResourceManager.GetString("ValueShouldNotBeBetweenXAndY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be greater than or equal to {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeGreaterThanOrEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeGreaterThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be greater than {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeGreaterThanX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeGreaterThanX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be infinity 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeInfinity {
            get {
                return ResourceManager.GetString("ValueShouldNotBeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be negative infinity 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeNegativeInfinity {
            get {
                return ResourceManager.GetString("ValueShouldNotBeNegativeInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be null 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeNull {
            get {
                return ResourceManager.GetString("ValueShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be of type {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeOfTypeX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be positive infinity 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBePositiveInfinity {
            get {
                return ResourceManager.GetString("ValueShouldNotBePositiveInfinity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be smaller than or equal to {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeSmallerThanOrEqualToX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeSmallerThanOrEqualToX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} should not be smaller than {1} 的本地化字符串。
        /// </summary>
        internal static string ValueShouldNotBeSmallerThanX {
            get {
                return ResourceManager.GetString("ValueShouldNotBeSmallerThanX", resourceCulture);
            }
        }
    }
}
